dist: xenial


language: python

matrix:
  include:
    - python: 3.7
      env: TOXENV=lint
    - python: 3.7
      env: TOXENV=py37
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - python: 3.7
      env: TOXENV=docs

install:
  - pip install tox

script:
  - travis_wait tox

